komga:
  baseUri: "http://localhost:25600"
  komgaUser: ""
  komgaPassword: ""
  eventListener:
    enabled: true
    metadataSeriesExcludeFilter: []
  metadataUpdate:
    default:
      aggregate: true
      mergeTags: true
      mergeGenres: true
      bookCovers: true
      seriesCovers: true
      overrideExistingCovers: false
      updateModes:
      - "API"
      - "COMIC_INFO"
      overrideComicInfo: true
      postProcessing:
        seriesTitle: true
        seriesTitleLanguage: "pt-br"
        alternativeSeriesTitles: true
        alternativeSeriesTitleLanguages:
        - "pt-br"
        - "en"
        - "ja"
        fallbackToAltTitle: true
        orderBooks: true
        readingDirectionValue: "WEBTOON"
        languageValue: "pt-br"
        scoreTagName: "score"
        originalPublisherTagName: "Original Publisher"
        publisherTagNames:
        - tagName: "Portuguese Publisher"
          language: "pt-BR"
kavita:
  metadataUpdate:
    default:
      mergeTags: true
      mergeGenres: true
      overrideExistingCovers: false
      updateModes:
      - "API"
      - "COMIC_INFO"
      postProcessing:
        seriesTitleLanguage: "pt-br"
        languageValue: "pt-br"

database:
  file: "/config/database.sqlite"

metadataProviders:
  defaultProviders:
    mangaUpdates:
      priority: 6
      enabled: true
    mal:
      priority: 7
    nautiljon:
      priority: 7
      enabled: true
    aniList:
      priority: 2
      enabled: true
    yenPress:
      priority: 8
      enabled: true
    kodansha:
      priority: 5
      enabled: true
    viz:
      priority: 9
      enabled: true
    bookWalker:
      priority: 4
      enabled: true
    mangaDex:
      priority: 1
      enabled: true
      coverLanguages:
      - "pt-br"
      - "en"
      - "ja"
    bangumi:
      priority: 3
      enabled: true
    comicVine:
      priority: 5
    hentag:
      priority: 5

notifications:
  templatesDirectory: "/config"

logLevel: "DEBUG"
