networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16

services:
  portainer:
    container_name: portainer
    hostname: portainer
    image: portainer/portainer-ee:lts
    restart: always
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9443:9443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      # - "/run/podman/podman.sock:/var/run/docker.sock"
      - "data:/data"
    networks:
      net:
        ipv4_address: 172.23.0.6

  portainer_agent:
    container_name: portainer-agent
    hostname: portainer_agent
    image: portainer/agent:2.27.3
    restart: always
    ports:
      - "9001:9001"
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes"
      - "/:/host"
    networks:
      net:
        ipv4_address: 172.23.0.7

volumes:
  data:
