services:
  manga-dlp:
    container_name: manga-dlp
    image: olofvndrhr/manga-dlp:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - manga-net
    volumes:
      - ~/.docker/manga-dlp/downloads:/app/downloads/
      - ~/.docker/manga-dlp/mangas.txt:/app/mangas.txt
      - TZ=America/Sao_Paulo
    command:
      [
        "manga-dlp",
        "--read",
        "/app/mangas.txt",
        "-l",
        "pt-br",
        "--chapters",
        "all",
        "--format",
        "cbz",
      ]

  kavita:
    container_name: kavita_read_server
    image: jvmilazz0/kavita:latest
    restart: unless-stopped
    volumes:
      - ~/.docker/kavita:/kavita/config
      - ~/.docker/manga-dlp/downloads:/manga
    ports:
      - "5000:5000"
    networks:
      - manga-net

networks:
  manga-net:
    name: mangadlp
    driver: bridge
