services:
  adguard-home:
    container_name: adguard-home
    hostname: adguard-home
    image: adguard/adguardhome:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    volumes:
      - ~/.docker/adguard-home/work:/opt/adguardhome/work
      - ~/.docker/adguard-home/conf:/opt/adguardhome/conf
    restart: unless-stopped