volumes:
  db:
  redis:

networks:
  kaizoku_network:
    driver: bridge

services:
  app:
    container_name: kaizoku
    image: ghcr.io/oae/kaizoku:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - KAIZOKU_PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ~/.docker/Manga/Library:/data
      - ~/.docker/Manga/Kaizoku/config:/config
      - /tmp:/logs
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - kaizoku_network

  redis:
    container_name: kaizoku_redis
    image: redis:7-alpine
    volumes:
      - redis:/data
    networks:
      - kaizoku_network

  db:
    container_name: kaizoku_db
    image: postgres:alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kaizoku"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - TZ=America/Sao_Paulo
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - kaizoku_network

  kavita:
    container_name: kaizoku_kavita
    image: jvmilazz0/kavita:latest
    restart: unless-stopped
    volumes:
      - ~/.docker/kavita:/kavita/config
      - ~/.docker/Manga/Library:/manga
    ports:
      - "5000:5000"
    networks:
      - kaizoku_network
