services:
  stremio:
    container_name: stremio
    image: tsaridas/stremio-docker:v1.1.8
    environment:
      - NO_CORS=1
    volumes:
       - "~/.docker/stremio-server:/root/.stremio-server"
    ports:
      - "11470:11470"
      - "8100:8100"
    deploy:
      resources:
        limits:
          memory: 1024M
    restart: unless-stopped
    network_mode: bridge
